[package]
name = "avis-imgv"
description = "Image viewer based on egui. Makes use of modern RAM amounts by loading images ahead of time for very fast responsiveness. Minimal UI with heavy use of shortcuts."
license = "GPL-3.0"
homepage = "https://github.com/hats-np/avis-imgv"
repository = "https://github.com/hats-np/avis-imgv"
version = "0.2.0"
edition = "2021"
readme = "README.md"
keywords = ["image_viewer", "image"]

[dependencies]
eframe = { version = "0.28.1" }
image = { version = "0.25.2", default-features = true }
serde = { version = "1.0.209" }
serde_json = { version = "1.0.127" }
directories = { version = "5.0.1" }
qcms = { version = "0.3.0" }
sqlite = { version = "0.36.1" }
regex = { version = "1.10.6" }
rfd = { version = "0.14.1" }
fast_image_resize = { version = "4.2.1" }
rand = { version = "0.8.5" }
notify = "6.1.1"
