gallery:
  name_format: "$(#File Name#)$( • ƒ#Aperture#)$( • #Shutter Speed#)$( • #ISO# ISO)"
  nr_loaded_images: 5
  should_wait: true
  metadata_tags:
    - Date/Time Original
    - Created Date
    - Camera Model Name
    - Lens Model
    - Focal Length
    - Aperture Value
    - Exposure Time
    - ISO
    - Image Size
    - Color Space
    - Directory
  frame_size_relative_to_image: 0.1
  scroll_navigation: true
  user_actions:
    - exec: "gimp {}"
      shortcut:
        key: 1
        modifiers:
          - alt
    - exec: "rm {}"
      shortcut:
        key: delete
        modifiers:
          - ctrl
      callback: Pop
    - exec:
      shortcut:
        key: f6
        modifiers: [ ]
      callback: Reload
    - exec:
      shortcut:
        key: f5
        modifiers: [ ]
      callback: ReloadAll
  context_menu:
    - exec: "gimp {}"
      description: "Open in GIMP"
    - exec: "darktable {.}.RAF"
      description: "Open RAW in Darktable"
    - exec: "rm {}"
      description: "Remove"
      callback: Pop
  delete_cmd: "rm {}"
  sc_fit:
    key: f
    modifiers: [ ]
  sc_frame:
    key: g
    modifiers: [ ]
  sc_metadata:
    key: i
    modifiers: [ ]
  sc_zoom:
    key: space
    modifiers: [ ]
  sc_next:
    key: right
    modifiers: [ ]
  sc_prev:
    key: left
    modifiers: [ ]
  sc_one_to_one:
    key: 1
    modifiers: [ ctrl ]


multi_gallery:
  images_per_row: 5
  preloaded_rows: 2
  simultaneous_load: 8
  margin_size: 10.0
  sc_scroll:
    key: space
    modifiers: [ ]
  sc_more_per_row:
    key: plus
    modifiers: [ ]
  sc_less_per_row:
    key: minus
    modifiers: [ ]
  context_menu:
    - exec: "gimp {}"
      description: "Open in GIMP"
    - exec: "darktable {.}.RAF"
      description: "Open RAW in Darktable"
    - exec: "rm {}"
      description: "Remove"
      callback: Pop

general:
  limit_cached: 100000
  output_icc_profile: srgb
  text_scaling: 1.5
  sc_toggle_gallery:
    key: escape
    modifiers: [ ]
  sc_exit:
    key: q
    modifiers:
      - alt
  sc_menu:
    key: F1
    modifiers: [ ]
  sc_navigator:
    key: l
    modifiers:
      - ctrl
  sc_dir_tree:
    key: t
    modifiers: [ ]
